//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.Resources.StringsResources", typeof(StringsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventario CyCSA.
        /// </summary>
        public static string CaptionCompany {
            get {
                return ResourceManager.GetString("CaptionCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas/Salidas de Inventario.
        /// </summary>
        public static string CaptionInventory {
            get {
                return ResourceManager.GetString("CaptionInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar eliminar.
        /// </summary>
        public static string CaptionOnDeleteRecord {
            get {
                return ResourceManager.GetString("CaptionOnDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string CaptionOnSave {
            get {
                return ResourceManager.GetString("CaptionOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código duplicado.
        /// </summary>
        public static string ErrorCategoryCodeDup {
            get {
                return ResourceManager.GetString("ErrorCategoryCodeDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un nombre de estado.
        /// </summary>
        public static string ErrorColumnStatus {
            get {
                return ResourceManager.GetString("ErrorColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar estado porque hay items dependen de él.
        /// </summary>
        public static string ErrorMsgCantDeleteStatus {
            get {
                return ResourceManager.GetString("ErrorMsgCantDeleteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se admite valor vacío.
        /// </summary>
        public static string ErrorMsgEmpty {
            get {
                return ResourceManager.GetString("ErrorMsgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un item.
        /// </summary>
        public static string ErrorMsgItemReport {
            get {
                return ResourceManager.GetString("ErrorMsgItemReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error.
        /// </summary>
        public static string ErrorMsgOcurred {
            get {
                return ResourceManager.GetString("ErrorMsgOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al guardar el registro.
        /// </summary>
        public static string ErrorMsgOnRecordSaved {
            get {
                return ResourceManager.GetString("ErrorMsgOnRecordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El almacén destino no puede ser el mismo que el almacén origen.
        /// </summary>
        public static string ErrorMsgOnWarehouseTransfer {
            get {
                return ResourceManager.GetString("ErrorMsgOnWarehouseTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los almacenes de origen y destino no puede ser iguales.
        /// </summary>
        public static string ErrorMsgSameWarehouse {
            get {
                return ResourceManager.GetString("ErrorMsgSameWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione un valor.
        /// </summary>
        public static string ErrorMsgSelectValue {
            get {
                return ResourceManager.GetString("ErrorMsgSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe item en bodega.
        /// </summary>
        public static string MessageNoItemInWarehouse {
            get {
                return ResourceManager.GetString("MessageNoItemInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún item seleccionado.
        /// </summary>
        public static string MessageNoItemSelected {
            get {
                return ResourceManager.GetString("MessageNoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay suficientes unidades en existencia.
        /// </summary>
        public static string MessageNoStock {
            get {
                return ResourceManager.GetString("MessageNoStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de la Empresa guardada.
        /// </summary>
        public static string MessageOnCompanyInfoSaved {
            get {
                return ResourceManager.GetString("MessageOnCompanyInfoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar el registro actual?.
        /// </summary>
        public static string MessageOnDeleteRecord {
            get {
                return ResourceManager.GetString("MessageOnDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item guardado!.
        /// </summary>
        public static string MessageOnRecordSaved {
            get {
                return ResourceManager.GetString("MessageOnRecordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción completada!.
        /// </summary>
        public static string MessageOnTransactionSave {
            get {
                return ResourceManager.GetString("MessageOnTransactionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún almacén seleccionado.
        /// </summary>
        public static string MessageWarehouseNoSelected {
            get {
                return ResourceManager.GetString("MessageWarehouseNoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El almacén aún contiene items con existencias.
        /// </summary>
        public static string MessageWarehouseNotEmpty {
            get {
                return ResourceManager.GetString("MessageWarehouseNotEmpty", resourceCulture);
            }
        }
    }
}
