//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"addresses")]
    public partial class Addresses : XPLiteObject
    {
        int faddress_id;
        [Key(true)]
        public int address_id
        {
            get { return faddress_id; }
            set { SetPropertyValue<int>("address_id", ref faddress_id, value); }
        }
        string fline1;
        [Size(500)]
        public string line1
        {
            get { return fline1; }
            set { SetPropertyValue<string>("line1", ref fline1, value); }
        }
        string fcity;
        [Size(50)]
        public string city
        {
            get { return fcity; }
            set { SetPropertyValue<string>("city", ref fcity, value); }
        }
        string fdepartment;
        [Size(50)]
        public string department
        {
            get { return fdepartment; }
            set { SetPropertyValue<string>("department", ref fdepartment, value); }
        }
        string fcountry;
        [Size(50)]
        public string country
        {
            get { return fcountry; }
            set { SetPropertyValue<string>("country", ref fcountry, value); }
        }
        Suppliers fsupplier_id;
        [Association(@"AddressesReferencesSuppliers")]
        public Suppliers supplier_id
        {
            get { return fsupplier_id; }
            set { SetPropertyValue<Suppliers>("supplier_id", ref fsupplier_id, value); }
        }
    }

}
