//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"appsettings")]
    public partial class Appsettings : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fkey;
        [Size(255)]
        public string key
        {
            get { return fkey; }
            set { SetPropertyValue<string>("key", ref fkey, value); }
        }
        string fsvalue;
        [Size(255)]
        public string svalue
        {
            get { return fsvalue; }
            set { SetPropertyValue<string>("svalue", ref fsvalue, value); }
        }
        string fcomment;
        [Size(255)]
        public string comment
        {
            get { return fcomment; }
            set { SetPropertyValue<string>("comment", ref fcomment, value); }
        }
    }

}
