//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"inventorytransaction")]
    public partial class Inventorytransaction : XPLiteObject
    {
        int ftransaction_id;
        [Key(true)]
        public int transaction_id
        {
            get { return ftransaction_id; }
            set { SetPropertyValue<int>("transaction_id", ref ftransaction_id, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>("date", ref fdate, value); }
        }
        string fdescription;
        [Size(500)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        double funits;
        public double units
        {
            get { return funits; }
            set { SetPropertyValue<double>("units", ref funits, value); }
        }
        string freferenceNumber;
        [Size(20)]
        public string referenceNumber
        {
            get { return freferenceNumber; }
            set { SetPropertyValue<string>("referenceNumber", ref freferenceNumber, value); }
        }
        bool fcreditInvoice;
        public bool creditInvoice
        {
            get { return fcreditInvoice; }
            set { SetPropertyValue<bool>("creditInvoice", ref fcreditInvoice, value); }
        }
        Products fproduct_id;
        [Association(@"InventorytransactionReferencesProducts")]
        public Products product_id
        {
            get { return fproduct_id; }
            set { SetPropertyValue<Products>("product_id", ref fproduct_id, value); }
        }
        Warehouse fwarehouse_id;
        [Association(@"InventorytransactionReferencesWarehouse")]
        public Warehouse warehouse_id
        {
            get { return fwarehouse_id; }
            set { SetPropertyValue<Warehouse>("warehouse_id", ref fwarehouse_id, value); }
        }
        Suppliers fsupplier_id;
        [Association(@"InventorytransactionReferencesSuppliers")]
        public Suppliers supplier_id
        {
            get { return fsupplier_id; }
            set { SetPropertyValue<Suppliers>("supplier_id", ref fsupplier_id, value); }
        }
        string fstoreKeeper;
        [Size(65)]
        public string storeKeeper
        {
            get { return fstoreKeeper; }
            set { SetPropertyValue<string>("storeKeeper", ref fstoreKeeper, value); }
        }
        Transactionreason ftransactionReason;
        [Association(@"InventorytransactionReferencesTransactionreason")]
        public Transactionreason transactionReason
        {
            get { return ftransactionReason; }
            set { SetPropertyValue<Transactionreason>("transactionReason", ref ftransactionReason, value); }
        }
    }

}
