//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"phonecarrier")]
    public partial class Phonecarrier : XPLiteObject
    {
        int fid;
        [Key]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fcompany;
        [Size(15)]
        public string company
        {
            get { return fcompany; }
            set { SetPropertyValue<string>("company", ref fcompany, value); }
        }
        [Association(@"Company_phonenumbersReferencesPhonecarrier")]
        public XPCollection<Company_phonenumbers> Company_phonenumbers { get { return GetCollection<Company_phonenumbers>("Company_phonenumbers"); } }
        [Association(@"Suppliers_phonenumberReferencesPhonecarrier")]
        public XPCollection<Suppliers_phonenumber> Suppliers_phonenumber { get { return GetCollection<Suppliers_phonenumber>("Suppliers_phonenumber"); } }
    }

}
