//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"products")]
    public partial class Products : XPLiteObject
    {
        int fproduct_id;
        [Key(true)]
        public int product_id
        {
            get { return fproduct_id; }
            set { SetPropertyValue<int>("product_id", ref fproduct_id, value); }
        }
        string fname;
        [Size(255)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        string fdescription;
        [Size(510)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        string fserialnumber;
        public string serialnumber
        {
            get { return fserialnumber; }
            set { SetPropertyValue<string>("serialnumber", ref fserialnumber, value); }
        }
        string fserie;
        [Size(25)]
        public string serie
        {
            get { return fserie; }
            set { SetPropertyValue<string>("serie", ref fserie, value); }
        }
        string fmodel;
        [Size(45)]
        public string model
        {
            get { return fmodel; }
            set { SetPropertyValue<string>("model", ref fmodel, value); }
        }
        string fpartnumber;
        [Size(20)]
        public string partnumber
        {
            get { return fpartnumber; }
            set { SetPropertyValue<string>("partnumber", ref fpartnumber, value); }
        }
        string flote;
        [Size(20)]
        public string lote
        {
            get { return flote; }
            set { SetPropertyValue<string>("lote", ref flote, value); }
        }
        bool fdiscontinued;
        public bool discontinued
        {
            get { return fdiscontinued; }
            set { SetPropertyValue<bool>("discontinued", ref fdiscontinued, value); }
        }
        DateTime fdiscontinued_date;
        public DateTime discontinued_date
        {
            get { return fdiscontinued_date; }
            set { SetPropertyValue<DateTime>("discontinued_date", ref fdiscontinued_date, value); }
        }
        double fweight;
        public double weight
        {
            get { return fweight; }
            set { SetPropertyValue<double>("weight", ref fweight, value); }
        }
        byte[] fpicture;
        [Size(SizeAttribute.Unlimited)]
        public byte[] picture
        {
            get { return fpicture; }
            set { SetPropertyValue<byte[]>("picture", ref fpicture, value); }
        }
        Category fcategory_id;
        [Indexed(Name = @"fk_Products_Category_idx")]
        [Association(@"ProductsReferencesCategory")]
        public Category category_id
        {
            get { return fcategory_id; }
            set { SetPropertyValue<Category>("category_id", ref fcategory_id, value); }
        }
        Brand fbrand_id;
        [Indexed(Name = @"fk_Products_Brand_idx")]
        [Association(@"ProductsReferencesBrand")]
        public Brand brand_id
        {
            get { return fbrand_id; }
            set { SetPropertyValue<Brand>("brand_id", ref fbrand_id, value); }
        }
        Unitofmeasure fuom_id;
        [Indexed(Name = @"fk_Products_UnitOfMeasure_idx")]
        [Association(@"ProductsReferencesUnitofmeasure")]
        public Unitofmeasure uom_id
        {
            get { return fuom_id; }
            set { SetPropertyValue<Unitofmeasure>("uom_id", ref fuom_id, value); }
        }
        string fbarcode_digits;
        [Size(128)]
        public string barcode_digits
        {
            get { return fbarcode_digits; }
            set { SetPropertyValue<string>("barcode_digits", ref fbarcode_digits, value); }
        }
        Status fStatus_idStatus;
        [Indexed(Name = @"fk_Products_Status_idx")]
        [Association(@"ProductsReferencesStatus")]
        public Status Status_idStatus
        {
            get { return fStatus_idStatus; }
            set { SetPropertyValue<Status>("Status_idStatus", ref fStatus_idStatus, value); }
        }
        string ffenergia;
        [Size(30)]
        public string fenergia
        {
            get { return ffenergia; }
            set { SetPropertyValue<string>("fenergia", ref ffenergia, value); }
        }
        string ftmante;
        [Size(30)]
        public string tmante
        {
            get { return ftmante; }
            set { SetPropertyValue<string>("tmante", ref ftmante, value); }
        }
        double ftotalStock;
        public double totalStock
        {
            get { return ftotalStock; }
            set { SetPropertyValue<double>("totalStock", ref ftotalStock, value); }
        }
        string fproductcode;
        [Indexed(Name = @"productcode_UNIQUE", Unique = true)]
        [Size(25)]
        public string productcode
        {
            get { return fproductcode; }
            set { SetPropertyValue<string>("productcode", ref fproductcode, value); }
        }
        [Association(@"InventorytransactionReferencesProducts")]
        public XPCollection<Inventorytransaction> Inventorytransactions { get { return GetCollection<Inventorytransaction>("Inventorytransactions"); } }
        [Association(@"PurchaseorderdetailsReferencesProducts")]
        public XPCollection<Purchaseorderdetails> PurchaseorderdetailsCollection { get { return GetCollection<Purchaseorderdetails>("PurchaseorderdetailsCollection"); } }
        [Association(@"StoredItemReferencesProducts")]
        public XPCollection<StoredItem> StoredItems { get { return GetCollection<StoredItem>("StoredItems"); } }
    }

}
