//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"secuence_data")]
    public partial class Secuence_data : XPLiteObject
    {
        string fname;
        [Key]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        uint fincrement;
        public uint increment
        {
            get { return fincrement; }
            set { SetPropertyValue<uint>("increment", ref fincrement, value); }
        }
        uint fmin_value;
        public uint min_value
        {
            get { return fmin_value; }
            set { SetPropertyValue<uint>("min_value", ref fmin_value, value); }
        }
        ulong fmax_value;
        public ulong max_value
        {
            get { return fmax_value; }
            set { SetPropertyValue<ulong>("max_value", ref fmax_value, value); }
        }
        ulong fcur_value;
        public ulong cur_value
        {
            get { return fcur_value; }
            set { SetPropertyValue<ulong>("cur_value", ref fcur_value, value); }
        }
        bool fcycle;
        public bool cycle
        {
            get { return fcycle; }
            set { SetPropertyValue<bool>("cycle", ref fcycle, value); }
        }
    }

}
