//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"status")]
    public partial class Status : XPLiteObject
    {
        int fidStatus;
        [Key(true)]
        public int idStatus
        {
            get { return fidStatus; }
            set { SetPropertyValue<int>("idStatus", ref fidStatus, value); }
        }
        string fstatus;
        [Size(25)]
        public string status
        {
            get { return fstatus; }
            set { SetPropertyValue<string>("status", ref fstatus, value); }
        }
        [Association(@"ProductsReferencesStatus")]
        public XPCollection<Products> ProductsCollection { get { return GetCollection<Products>("ProductsCollection"); } }
    }

}
