//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"storeditem")]
    public partial class Stored : XPLiteObject
    {
        int fstored_id;
        [Key(true)]
        public int stored_id
        {
            get { return fstored_id; }
            set { SetPropertyValue<int>("stored_id", ref fstored_id, value); }
        }
        string fboxnumber;
        [Size(30)]
        public string boxnumber
        {
            get { return fboxnumber; }
            set { SetPropertyValue<string>("boxnumber", ref fboxnumber, value); }
        }
        string fshelf;
        [Size(45)]
        public string shelf
        {
            get { return fshelf; }
            set { SetPropertyValue<string>("shelf", ref fshelf, value); }
        }
        string frow;
        [Size(15)]
        public string row
        {
            get { return frow; }
            set { SetPropertyValue<string>("row", ref frow, value); }
        }
        string fposition;
        [Size(15)]
        public string position
        {
            get { return fposition; }
            set { SetPropertyValue<string>("position", ref fposition, value); }
        }
        double fquantityInHand;
        public double quantityInHand
        {
            get { return fquantityInHand; }
            set { SetPropertyValue<double>("quantityInHand", ref fquantityInHand, value); }
        }
        double freorderQuantity;
        public double reorderQuantity
        {
            get { return freorderQuantity; }
            set { SetPropertyValue<double>("reorderQuantity", ref freorderQuantity, value); }
        }
        Products fproduct_id;
        [Association(@"StoredReferencesProducts")]
        public Products product_id
        {
            get { return fproduct_id; }
            set { SetPropertyValue<Products>("product_id", ref fproduct_id, value); }
        }
        Warehouse fwarehouse_id;
        [Association(@"StoredReferencesWarehouse")]
        public Warehouse warehouse_id
        {
            get { return fwarehouse_id; }
            set { SetPropertyValue<Warehouse>("warehouse_id", ref fwarehouse_id, value); }
        }
    }

}
