//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData Execnextval(Session session, long RETURN_VALUE, string seqname)
        {
            return session.ExecuteSproc("nextval", new OperandValue(RETURN_VALUE), new OperandValue(seqname));
        }
    }
}
