//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"suppliers")]
    public partial class Suppliers : XPLiteObject
    {
        int fsupplier_id;
        [Key(true)]
        public int supplier_id
        {
            get { return fsupplier_id; }
            set { SetPropertyValue<int>("supplier_id", ref fsupplier_id, value); }
        }
        string fsuppliername;
        public string suppliername
        {
            get { return fsuppliername; }
            set { SetPropertyValue<string>("suppliername", ref fsuppliername, value); }
        }
        string fcontactname;
        public string contactname
        {
            get { return fcontactname; }
            set { SetPropertyValue<string>("contactname", ref fcontactname, value); }
        }
        string ffaxnumber;
        [Size(15)]
        public string faxnumber
        {
            get { return ffaxnumber; }
            set { SetPropertyValue<string>("faxnumber", ref ffaxnumber, value); }
        }
        string femail;
        [Size(120)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>("email", ref femail, value); }
        }
        string fwebsite;
        [Size(150)]
        public string website
        {
            get { return fwebsite; }
            set { SetPropertyValue<string>("website", ref fwebsite, value); }
        }
        string fnotes;
        [Size(SizeAttribute.Unlimited)]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        bool factive;
        public bool active
        {
            get { return factive; }
            set { SetPropertyValue<bool>("active", ref factive, value); }
        }
        [Association(@"AddressesReferencesSuppliers")]
        public XPCollection<Addresses> AddressesCollection { get { return GetCollection<Addresses>("AddressesCollection"); } }
        [Association(@"InventorytransactionReferencesSuppliers")]
        public XPCollection<Inventorytransaction> Inventorytransactions { get { return GetCollection<Inventorytransaction>("Inventorytransactions"); } }
        [Association(@"Suppliers_phonenumberReferencesSuppliers")]
        public XPCollection<Suppliers_phonenumber> Suppliers_phonenumber { get { return GetCollection<Suppliers_phonenumber>("Suppliers_phonenumber"); } }
    }

}
