//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"suppliers_phonenumber")]
    public partial class Suppliers_phonenumber : XPLiteObject
    {
        int fidSuppliers_PhoneNumber;
        [Key(true)]
        public int idSuppliers_PhoneNumber
        {
            get { return fidSuppliers_PhoneNumber; }
            set { SetPropertyValue<int>("idSuppliers_PhoneNumber", ref fidSuppliers_PhoneNumber, value); }
        }
        Phonecarrier fphonecarrier;
        [Association(@"Suppliers_phonenumberReferencesPhonecarrier")]
        public Phonecarrier phonecarrier
        {
            get { return fphonecarrier; }
            set { SetPropertyValue<Phonecarrier>("phonecarrier", ref fphonecarrier, value); }
        }
        Suppliers fsupplier_id;
        [Association(@"Suppliers_phonenumberReferencesSuppliers")]
        public Suppliers supplier_id
        {
            get { return fsupplier_id; }
            set { SetPropertyValue<Suppliers>("supplier_id", ref fsupplier_id, value); }
        }
        string fphoneNumber;
        [Size(15)]
        public string phoneNumber
        {
            get { return fphoneNumber; }
            set { SetPropertyValue<string>("phoneNumber", ref fphoneNumber, value); }
        }
        bool fisCellular;
        public bool isCellular
        {
            get { return fisCellular; }
            set { SetPropertyValue<bool>("isCellular", ref fisCellular, value); }
        }
        bool factive;
        public bool active
        {
            get { return factive; }
            set { SetPropertyValue<bool>("active", ref factive, value); }
        }
    }

}
