//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"unitofmeasure")]
    public partial class Unitofmeasure : XPLiteObject
    {
        int fuom_id;
        [Key(true)]
        public int uom_id
        {
            get { return fuom_id; }
            set { SetPropertyValue<int>("uom_id", ref fuom_id, value); }
        }
        string fabbreviation;
        [Size(10)]
        public string abbreviation
        {
            get { return fabbreviation; }
            set { SetPropertyValue<string>("abbreviation", ref fabbreviation, value); }
        }
        string fdescription;
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        [Association(@"ProductsReferencesUnitofmeasure")]
        public XPCollection<Products> ProductsCollection { get { return GetCollection<Products>("ProductsCollection"); } }
    }

}
