//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"user")]
    public partial class User : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fusername;
        [Size(60)]
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>("username", ref fusername, value); }
        }
        string fpassword;
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>("password", ref fpassword, value); }
        }
        string frol;
        [Size(10)]
        public string rol
        {
            get { return frol; }
            set { SetPropertyValue<string>("rol", ref frol, value); }
        }
    }

}
