//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Inventory.ORMDataModelCode
{

    [Persistent(@"warehouse")]
    public partial class Warehouse : XPLiteObject
    {
        int fwarehouse_id;
        [Key(true)]
        public int warehouse_id
        {
            get { return fwarehouse_id; }
            set { SetPropertyValue<int>("warehouse_id", ref fwarehouse_id, value); }
        }
        string fname;
        [Size(45)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        string fdescription;
        [Size(255)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        string flocation;
        [Size(255)]
        public string location
        {
            get { return flocation; }
            set { SetPropertyValue<string>("location", ref flocation, value); }
        }
        Project fproject_id;
        [Association(@"WarehouseReferencesProject")]
        public Project project_id
        {
            get { return fproject_id; }
            set { SetPropertyValue<Project>("project_id", ref fproject_id, value); }
        }
        [Association(@"InventorytransactionReferencesWarehouse")]
        public XPCollection<Inventorytransaction> Inventorytransactions { get { return GetCollection<Inventorytransaction>("Inventorytransactions"); } }
        [Association(@"StoredItemReferencesWarehouse")]
        public XPCollection<StoredItem> StoredItems { get { return GetCollection<StoredItem>("StoredItems"); } }
    }

}
