//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace Inventory.ORMDataModel {

	[Persistent(@"company_phonenumbers")]
	public partial class Company_phonenumbers : XPLiteObject {
		int fidCompany_PhoneNumbers;
		[Key(true)]
		public int idCompany_PhoneNumbers {
			get { return fidCompany_PhoneNumbers; }
			set { SetPropertyValue<int>("idCompany_PhoneNumbers", ref fidCompany_PhoneNumbers, value); }
		}
		Company fcompany_id;
		[Association(@"Company_phonenumbersReferencesCompany")]
		public Company company_id {
			get { return fcompany_id; }
			set { SetPropertyValue<Company>("company_id", ref fcompany_id, value); }
		}
		Phonenumbers fphoneNumbers_id;
		[Association(@"Company_phonenumbersReferencesPhonenumbers")]
		public Phonenumbers phoneNumbers_id {
			get { return fphoneNumbers_id; }
			set { SetPropertyValue<Phonenumbers>("phoneNumbers_id", ref fphoneNumbers_id, value); }
		}
	}

}
