//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace Inventory.ORMDataModel {

	[Persistent(@"inventorytransaction")]
	public partial class Inventorytransaction : XPLiteObject {
		int ftransaction_id;
		[Key(true)]
		public int transaction_id {
			get { return ftransaction_id; }
			set { SetPropertyValue<int>("transaction_id", ref ftransaction_id, value); }
		}
		DateTime ftransactionDate;
		public DateTime transactionDate {
			get { return ftransactionDate; }
			set { SetPropertyValue<DateTime>("transactionDate", ref ftransactionDate, value); }
		}
		string ftransactionDescription;
		[Size(500)]
		public string transactionDescription {
			get { return ftransactionDescription; }
			set { SetPropertyValue<string>("transactionDescription", ref ftransactionDescription, value); }
		}
		int funitsOrdered;
		public int unitsOrdered {
			get { return funitsOrdered; }
			set { SetPropertyValue<int>("unitsOrdered", ref funitsOrdered, value); }
		}
		int funitsReceived;
		public int unitsReceived {
			get { return funitsReceived; }
			set { SetPropertyValue<int>("unitsReceived", ref funitsReceived, value); }
		}
		int funitsUsed;
		public int unitsUsed {
			get { return funitsUsed; }
			set { SetPropertyValue<int>("unitsUsed", ref funitsUsed, value); }
		}
		int funitsReturned;
		public int unitsReturned {
			get { return funitsReturned; }
			set { SetPropertyValue<int>("unitsReturned", ref funitsReturned, value); }
		}
		Products fproduct_id;
		[Association(@"InventorytransactionReferencesProducts")]
		public Products product_id {
			get { return fproduct_id; }
			set { SetPropertyValue<Products>("product_id", ref fproduct_id, value); }
		}
		Warehouse fwarehouse_id;
		[Association(@"InventorytransactionReferencesWarehouse")]
		public Warehouse warehouse_id {
			get { return fwarehouse_id; }
			set { SetPropertyValue<Warehouse>("warehouse_id", ref fwarehouse_id, value); }
		}
	}

}
