//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace Inventory.ORMDataModel {


    [Persistent(@"phonenumbers")]
    public partial class Phonenumbers : XPLiteObject
    {
        int fphoneNumbers_id;
          [Key(true)]
        public int phoneNumbers_id
        {
            get { return fphoneNumbers_id; }
            set { SetPropertyValue<int>("phoneNumbers_id", ref fphoneNumbers_id, value); }
        }
        string fphoneNumber;
        [Size(15)]
        public string phoneNumber
        {
            get { return fphoneNumber; }
            set { SetPropertyValue<string>("phoneNumber", ref fphoneNumber, value); }
        }
        sbyte ftype;
        public sbyte type
        {
            get { return ftype; }
            set { SetPropertyValue<sbyte>("type", ref ftype, value); }
        }
        string fcompany;
        [Size(15)]
        public string company
        {
            get { return fcompany; }
            set { SetPropertyValue<string>("company", ref fcompany, value); }
        }
        sbyte fstatus;
        public sbyte status
        {
            get { return fstatus; }
            set { SetPropertyValue<sbyte>("status", ref fstatus, value); }
        }
        [Association(@"Company_phonenumbersReferencesPhonenumbers", typeof(Company_phonenumbers))]
        public XPCollection<Company_phonenumbers> Company_phonenumbers { get { return GetCollection<Company_phonenumbers>("Company_phonenumbers"); } }
        [Association(@"Suppliers_phonenumberReferencesPhonenumbers", typeof(Suppliers_phonenumber))]
        public XPCollection<Suppliers_phonenumber> Suppliers_phonenumber { get { return GetCollection<Suppliers_phonenumber>("Suppliers_phonenumber"); } }
    }
}
