//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace Inventory.ORMDataModel {

	[Persistent(@"purchaseorderdetails")]
	public partial class Purchaseorderdetails : XPLiteObject {
		int fidPurchaseOrderDetails;
		[Key(true)]
		public int idPurchaseOrderDetails {
			get { return fidPurchaseOrderDetails; }
			set { SetPropertyValue<int>("idPurchaseOrderDetails", ref fidPurchaseOrderDetails, value); }
		}
		double funitPrice;
		public double unitPrice {
			get { return funitPrice; }
			set { SetPropertyValue<double>("unitPrice", ref funitPrice, value); }
		}
		int funitsOrdered;
		public int unitsOrdered {
			get { return funitsOrdered; }
			set { SetPropertyValue<int>("unitsOrdered", ref funitsOrdered, value); }
		}
		double fSubtotal;
		public double Subtotal {
			get { return fSubtotal; }
			set { SetPropertyValue<double>("Subtotal", ref fSubtotal, value); }
		}
		double fIVA;
		public double IVA {
			get { return fIVA; }
			set { SetPropertyValue<double>("IVA", ref fIVA, value); }
		}
		double fTotal;
		public double Total {
			get { return fTotal; }
			set { SetPropertyValue<double>("Total", ref fTotal, value); }
		}
		Products fproduct_id;
		[Association(@"PurchaseorderdetailsReferencesProducts")]
		public Products product_id {
			get { return fproduct_id; }
			set { SetPropertyValue<Products>("product_id", ref fproduct_id, value); }
		}
		Purchaseorders fpurchaseOrder_id;
		[Association(@"PurchaseorderdetailsReferencesPurchaseorders")]
		public Purchaseorders purchaseOrder_id {
			get { return fpurchaseOrder_id; }
			set { SetPropertyValue<Purchaseorders>("purchaseOrder_id", ref fpurchaseOrder_id, value); }
		}
	}

}
