//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace Inventory.ORMDataModel {

	[Persistent(@"purchaseorders")]
	public partial class Purchaseorders : XPLiteObject {
		int fpurchaseOrder_id;
		[Key(true)]
		public int purchaseOrder_id {
			get { return fpurchaseOrder_id; }
			set { SetPropertyValue<int>("purchaseOrder_id", ref fpurchaseOrder_id, value); }
		}
		string fpurchaseOrderNumber;
		[Size(45)]
		public string purchaseOrderNumber {
			get { return fpurchaseOrderNumber; }
			set { SetPropertyValue<string>("purchaseOrderNumber", ref fpurchaseOrderNumber, value); }
		}
		string fpurchaseOrderDescription;
		[Size(510)]
		public string purchaseOrderDescription {
			get { return fpurchaseOrderDescription; }
			set { SetPropertyValue<string>("purchaseOrderDescription", ref fpurchaseOrderDescription, value); }
		}
		DateTime forderDate;
		public DateTime orderDate {
			get { return forderDate; }
			set { SetPropertyValue<DateTime>("orderDate", ref forderDate, value); }
		}
		DateTime fdatePromised;
		public DateTime datePromised {
			get { return fdatePromised; }
			set { SetPropertyValue<DateTime>("datePromised", ref fdatePromised, value); }
		}
		DateTime fshipDate;
		public DateTime shipDate {
			get { return fshipDate; }
			set { SetPropertyValue<DateTime>("shipDate", ref fshipDate, value); }
		}
		double ffreightCharge;
		public double freightCharge {
			get { return ffreightCharge; }
			set { SetPropertyValue<double>("freightCharge", ref ffreightCharge, value); }
		}
		[Association(@"PurchaseorderdetailsReferencesPurchaseorders", typeof(Purchaseorderdetails))]
		public XPCollection<Purchaseorderdetails> PurchaseorderdetailsCollection { get { return GetCollection<Purchaseorderdetails>("PurchaseorderdetailsCollection"); } }
	}

}
